name: "CI"
on:
  push:
  pull_request:

jobs:
  build:
    name: build ${{ matrix.os }} app
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup on non-Linux
        uses: actions-rust-lang/setup-rust-toolchain@v1
        if: matrix.os != 'ubuntu-latest'

      - name: setup on Linux
        uses: actions-rust-lang/setup-rust-toolchain@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          target: x86_64-unknown-linux-musl

      - name: build on non-Linux
        if: matrix.os != 'ubuntu-latest'
        run: cargo build --release

      - name: build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install -y musl-tools
          cargo build --release --target x86_64-unknown-linux-musl


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Build
          path: |
            target/x86_64-unknown-linux-musl/release/Course-order-suggestion
            target/release/Course-order-suggestion
            target/release/Course-order-suggestion.exe
