name: "CI"
on:
  push:
  pull_request:

jobs:
  build:
    name: build ${{ matrix.os }} app
    strategy:
      matrix:
        os: [macos-latest, macos-13, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }} Build
          path: |
            target/release/Course-order-suggestion
            target/release/Course-order-suggestion.exe
